### ISSUE TITLE
Some favorited channels don't show in the sidebar.

### ISSUE THREAD

**Issue by samizsodope** [MarkM-dev/Previews-client#122] opened 2023-02-11 08:37 UTC
Some of my favorited channels aren't showing up in the side bar when they are live. I notice this happens the most with streams that have low viewership. 

I posted on the google chrome store reviews and they said there might be an interference on my browser. Any help?

**Comment by MarkM-dev** [comment] 2023-02-11 13:43
1. how many users are in your sidebar? twitch has some limitation to the amount of live streamers it shows in the sidebar.
2. browser?
3. perhaps other browser extensions are causing it? you can try disabling all extensions but previews, refresh tabs after.
4. more interference can be caused by unusual elements present on the sidebar streamer card, maybe sometimes there's some icon on them that is breaking them?

**Comment by MarkM-dev** [comment] 2023-06-05 19:32
should be fixed now.

**Closed by MarkM-dev** 2023-06-05 19:32 UTC
